//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrentlyListening.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations_pt {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations_pt() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CurrentlyListening.Resources.Translations.pt", typeof(Translations_pt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artista.
        /// </summary>
        internal static string ARTIST {
            get {
                return ResourceManager.GetString("ARTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorização bem-sucedida. Você pode fechar esta janela..
        /// </summary>
        internal static string AUTH_SUCCESS {
            get {
                return ResourceManager.GetString("AUTH_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID do cliente.
        /// </summary>
        internal static string CLIENT_ID {
            get {
                return ResourceManager.GetString("CLIENT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segredo do cliente.
        /// </summary>
        internal static string CLIENT_SECRET {
            get {
                return ResourceManager.GetString("CLIENT_SECRET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criado por .
        /// </summary>
        internal static string CREATED_BY {
            get {
                return ResourceManager.GetString("CREATED_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caminho do arquivo salvo:\n{dialog.FileName}.
        /// </summary>
        internal static string FILE_SAVED {
            get {
                return ResourceManager.GetString("FILE_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvo.
        /// </summary>
        internal static string FILE_SAVED_CAPTION {
            get {
                return ResourceManager.GetString("FILE_SAVED_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajuda.
        /// </summary>
        internal static string HELP {
            get {
                return ResourceManager.GetString("HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opcionalmente, antes de começar, registre seu próprio aplicativo em.
        /// </summary>
        internal static string HELP_1_0 {
            get {
                return ResourceManager.GetString("HELP_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione &quot;Web API&quot; como plataforma e defina a URL de retorno para: http://127.0.0.1:5000/callback. Uma vez criado, você encontrará o Client ID e o Client Secret no painel da aplicação — necessários para o login..
        /// </summary>
        internal static string HELP_1_1 {
            get {
                return ResourceManager.GetString("HELP_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Clique em &quot;Entrar no Spotify&quot; para autenticar sua conta..
        /// </summary>
        internal static string HELP_2 {
            get {
                return ResourceManager.GetString("HELP_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Escolha quais detalhes da faixa mostrar: Artista, Título da música e/ou Tempo..
        /// </summary>
        internal static string HELP_3 {
            get {
                return ResourceManager.GetString("HELP_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Use &quot;Definir local do arquivo de saída&quot; para escolher onde as informações da faixa serão gravadas..
        /// </summary>
        internal static string HELP_4 {
            get {
                return ResourceManager.GetString("HELP_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Clique em &quot;Atualizar exibição&quot; para aplicar as alterações. O arquivo é atualizado automaticamente enquanto o aplicativo está em execução..
        /// </summary>
        internal static string HELP_5 {
            get {
                return ResourceManager.GetString("HELP_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dica: Você pode usar o arquivo de saída em sobreposições OBS ou widgets de stream..
        /// </summary>
        internal static string HELP_TIP {
            get {
                return ResourceManager.GetString("HELP_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Como usar o aplicativo CurrentlyListening.
        /// </summary>
        internal static string HOW_TO_USE_APP {
            get {
                return ResourceManager.GetString("HOW_TO_USE_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algo deu errado com os dados de login, por favor reautorize.
        /// </summary>
        internal static string LOGIN_FAILED {
            get {
                return ResourceManager.GetString("LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar no Spotify.
        /// </summary>
        internal static string LOGIN_SPOTIFY {
            get {
                return ResourceManager.GetString("LOGIN_SPOTIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login realizado com sucesso..
        /// </summary>
        internal static string LOGIN_SUCCESS {
            get {
                return ResourceManager.GetString("LOGIN_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nada está tocando no momento..
        /// </summary>
        internal static string NOTHING_PLAYING {
            get {
                return ResourceManager.GetString("NOTHING_PLAYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pré-visualização da saída:.
        /// </summary>
        internal static string OUTPUT_PREVIEW {
            get {
                return ResourceManager.GetString("OUTPUT_PREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar local do arquivo de saída.
        /// </summary>
        internal static string SELECT_OUTPUT {
            get {
                return ResourceManager.GetString("SELECT_OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definir local do arquivo de saída.
        /// </summary>
        internal static string SET_OUTPUT_LOCATION {
            get {
                return ResourceManager.GetString("SET_OUTPUT_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título da música.
        /// </summary>
        internal static string SONG_TITLE {
            get {
                return ResourceManager.GetString("SONG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo (Progresso/Duração).
        /// </summary>
        internal static string TIME {
            get {
                return ResourceManager.GetString("TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opções de exibição da faixa:.
        /// </summary>
        internal static string TRACK_DISPLAY_OPTIONS {
            get {
                return ResourceManager.GetString("TRACK_DISPLAY_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artista desconhecido.
        /// </summary>
        internal static string UNKNOWN_ARTIST {
            get {
                return ResourceManager.GetString("UNKNOWN_ARTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título desconhecido.
        /// </summary>
        internal static string UNKNOWN_TITLE {
            get {
                return ResourceManager.GetString("UNKNOWN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualizar exibição.
        /// </summary>
        internal static string UPDATE_DISPLAY {
            get {
                return ResourceManager.GetString("UPDATE_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usar ID e segredo personalizados.
        /// </summary>
        internal static string USE_CUSTOM_CREDENTIALS {
            get {
                return ResourceManager.GetString("USE_CUSTOM_CREDENTIALS", resourceCulture);
            }
        }
    }
}
