//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrentlyListening.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations_cs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations_cs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CurrentlyListening.Resources.Translations.cs", typeof(Translations_cs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpret.
        /// </summary>
        internal static string ARTIST {
            get {
                return ResourceManager.GetString("ARTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizace byla úspěšná. Můžete zavřít toto okno..
        /// </summary>
        internal static string AUTH_SUCCESS {
            get {
                return ResourceManager.GetString("AUTH_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID klienta.
        /// </summary>
        internal static string CLIENT_ID {
            get {
                return ResourceManager.GetString("CLIENT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tajný klíč klienta.
        /// </summary>
        internal static string CLIENT_SECRET {
            get {
                return ResourceManager.GetString("CLIENT_SECRET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořil .
        /// </summary>
        internal static string CREATED_BY {
            get {
                return ResourceManager.GetString("CREATED_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cesta k souboru byla uložena:\n{dialog.FileName}.
        /// </summary>
        internal static string FILE_SAVED {
            get {
                return ResourceManager.GetString("FILE_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uloženo.
        /// </summary>
        internal static string FILE_SAVED_CAPTION {
            get {
                return ResourceManager.GetString("FILE_SAVED_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nápověda.
        /// </summary>
        internal static string HELP {
            get {
                return ResourceManager.GetString("HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volitelně si před začátkem zaregistrujte vlastní aplikaci na.
        /// </summary>
        internal static string HELP_1_0 {
            get {
                return ResourceManager.GetString("HELP_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jako platformu zvolte &quot;Web API&quot; a nastavte návratovou URL na: http://127.0.0.1:5000/callback. Po vytvoření najdete Client ID a Client Secret v dashboardu aplikace — ty jsou potřeba k přihlášení..
        /// </summary>
        internal static string HELP_1_1 {
            get {
                return ResourceManager.GetString("HELP_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Klikněte na &quot;Přihlásit se ke Spotify&quot; pro ověření svého účtu..
        /// </summary>
        internal static string HELP_2 {
            get {
                return ResourceManager.GetString("HELP_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Vyberte, které informace o skladbě se mají zobrazit: Umělec, Název skladby a/nebo Čas..
        /// </summary>
        internal static string HELP_3 {
            get {
                return ResourceManager.GetString("HELP_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Použijte &quot;Nastavit umístění výstupního souboru&quot; pro výběr místa uložení informací o skladbě..
        /// </summary>
        internal static string HELP_4 {
            get {
                return ResourceManager.GetString("HELP_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Klikněte na &quot;Aktualizovat zobrazení&quot; pro použití změn. Soubor se automaticky aktualizuje během běhu aplikace..
        /// </summary>
        internal static string HELP_5 {
            get {
                return ResourceManager.GetString("HELP_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: Výstupní soubor můžete použít v OBS překryvech nebo streamovacích widgetech..
        /// </summary>
        internal static string HELP_TIP {
            get {
                return ResourceManager.GetString("HELP_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jak používat aplikaci CurrentlyListening.
        /// </summary>
        internal static string HOW_TO_USE_APP {
            get {
                return ResourceManager.GetString("HOW_TO_USE_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Došlo k chybě s přihlašovacími údaji, prosím znovu autorizujte.
        /// </summary>
        internal static string LOGIN_FAILED {
            get {
                return ResourceManager.GetString("LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlásit se ke Spotify.
        /// </summary>
        internal static string LOGIN_SPOTIFY {
            get {
                return ResourceManager.GetString("LOGIN_SPOTIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlášení bylo úspěšné..
        /// </summary>
        internal static string LOGIN_SUCCESS {
            get {
                return ResourceManager.GetString("LOGIN_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Momentálně nic nehraje..
        /// </summary>
        internal static string NOTHING_PLAYING {
            get {
                return ResourceManager.GetString("NOTHING_PLAYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Náhled výstupu:.
        /// </summary>
        internal static string OUTPUT_PREVIEW {
            get {
                return ResourceManager.GetString("OUTPUT_PREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte umístění výstupního souboru.
        /// </summary>
        internal static string SELECT_OUTPUT {
            get {
                return ResourceManager.GetString("SELECT_OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavit umístění výstupního souboru.
        /// </summary>
        internal static string SET_OUTPUT_LOCATION {
            get {
                return ResourceManager.GetString("SET_OUTPUT_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název skladby.
        /// </summary>
        internal static string SONG_TITLE {
            get {
                return ResourceManager.GetString("SONG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čas (Průběh/Doba trvání).
        /// </summary>
        internal static string TIME {
            get {
                return ResourceManager.GetString("TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Možnosti zobrazení skladeb:.
        /// </summary>
        internal static string TRACK_DISPLAY_OPTIONS {
            get {
                return ResourceManager.GetString("TRACK_DISPLAY_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neznámý interpret.
        /// </summary>
        internal static string UNKNOWN_ARTIST {
            get {
                return ResourceManager.GetString("UNKNOWN_ARTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neznámý název.
        /// </summary>
        internal static string UNKNOWN_TITLE {
            get {
                return ResourceManager.GetString("UNKNOWN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualizovat zobrazení.
        /// </summary>
        internal static string UPDATE_DISPLAY {
            get {
                return ResourceManager.GetString("UPDATE_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Použít vlastní ID klienta a tajný klíč.
        /// </summary>
        internal static string USE_CUSTOM_CREDENTIALS {
            get {
                return ResourceManager.GetString("USE_CUSTOM_CREDENTIALS", resourceCulture);
            }
        }
    }
}
