//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrentlyListening.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations_es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CurrentlyListening.Resources.Translations.es", typeof(Translations_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artista.
        /// </summary>
        internal static string ARTIST {
            get {
                return ResourceManager.GetString("ARTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorización exitosa. Puedes cerrar esta ventana..
        /// </summary>
        internal static string AUTH_SUCCESS {
            get {
                return ResourceManager.GetString("AUTH_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID del cliente.
        /// </summary>
        internal static string CLIENT_ID {
            get {
                return ResourceManager.GetString("CLIENT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secreto del cliente.
        /// </summary>
        internal static string CLIENT_SECRET {
            get {
                return ResourceManager.GetString("CLIENT_SECRET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        internal static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creado por .
        /// </summary>
        internal static string CREATED_BY {
            get {
                return ResourceManager.GetString("CREATED_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta del archivo guardada:\n{dialog.FileName}.
        /// </summary>
        internal static string FILE_SAVED {
            get {
                return ResourceManager.GetString("FILE_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardado.
        /// </summary>
        internal static string FILE_SAVED_CAPTION {
            get {
                return ResourceManager.GetString("FILE_SAVED_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayuda.
        /// </summary>
        internal static string HELP {
            get {
                return ResourceManager.GetString("HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opcionalmente, antes de comenzar, registre su propia aplicación en.
        /// </summary>
        internal static string HELP_1_0 {
            get {
                return ResourceManager.GetString("HELP_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona &quot;Web API&quot; como plataforma y establece la URL de redirección en: http://127.0.0.1:5000/callback. Una vez creada, encontrarás el ID de cliente y el secreto de cliente en el panel de tu aplicación — necesarios para iniciar sesión...
        /// </summary>
        internal static string HELP_1_1 {
            get {
                return ResourceManager.GetString("HELP_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Haga clic en &quot;Iniciar sesión en Spotify&quot; para autenticar su cuenta..
        /// </summary>
        internal static string HELP_2 {
            get {
                return ResourceManager.GetString("HELP_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Elija qué detalles de la pista mostrar: Artista, Título de la canción y/o Tiempo..
        /// </summary>
        internal static string HELP_3 {
            get {
                return ResourceManager.GetString("HELP_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Use &quot;Establecer ubicación del archivo de salida&quot; para elegir dónde se escribirá la información de la pista..
        /// </summary>
        internal static string HELP_4 {
            get {
                return ResourceManager.GetString("HELP_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Haga clic en &quot;Actualizar visualización&quot; para aplicar los cambios. El archivo se actualiza automáticamente mientras la aplicación se está ejecutando..
        /// </summary>
        internal static string HELP_5 {
            get {
                return ResourceManager.GetString("HELP_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consejo: puede usar el archivo de salida en superposiciones OBS o widgets de transmisión..
        /// </summary>
        internal static string HELP_TIP {
            get {
                return ResourceManager.GetString("HELP_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cómo usar la aplicación CurrentlyListening.
        /// </summary>
        internal static string HOW_TO_USE_APP {
            get {
                return ResourceManager.GetString("HOW_TO_USE_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algo salió mal con los datos de inicio de sesión, por favor vuelve a autorizar.
        /// </summary>
        internal static string LOGIN_FAILED {
            get {
                return ResourceManager.GetString("LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión en Spotify.
        /// </summary>
        internal static string LOGIN_SPOTIFY {
            get {
                return ResourceManager.GetString("LOGIN_SPOTIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio de sesión exitoso..
        /// </summary>
        internal static string LOGIN_SUCCESS {
            get {
                return ResourceManager.GetString("LOGIN_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La aplicación se ha minimizado. Haz clic en el icono de la bandeja para mostrarla..
        /// </summary>
        internal static string MINIMIZE_NOTIFICATION_TEXT {
            get {
                return ResourceManager.GetString("MINIMIZE_NOTIFICATION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualmente no se está reproduciendo nada..
        /// </summary>
        internal static string NOTHING_PLAYING {
            get {
                return ResourceManager.GetString("NOTHING_PLAYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vista previa de salida:.
        /// </summary>
        internal static string OUTPUT_PREVIEW {
            get {
                return ResourceManager.GetString("OUTPUT_PREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar ubicación del archivo de salida.
        /// </summary>
        internal static string SELECT_OUTPUT {
            get {
                return ResourceManager.GetString("SELECT_OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establecer ubicación del archivo de salida.
        /// </summary>
        internal static string SET_OUTPUT_LOCATION {
            get {
                return ResourceManager.GetString("SET_OUTPUT_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título de la canción.
        /// </summary>
        internal static string SONG_TITLE {
            get {
                return ResourceManager.GetString("SONG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo (Progreso/Duración).
        /// </summary>
        internal static string TIME {
            get {
                return ResourceManager.GetString("TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opciones de visualización de pista:.
        /// </summary>
        internal static string TRACK_DISPLAY_OPTIONS {
            get {
                return ResourceManager.GetString("TRACK_DISPLAY_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artista desconocido.
        /// </summary>
        internal static string UNKNOWN_ARTIST {
            get {
                return ResourceManager.GetString("UNKNOWN_ARTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título desconocido.
        /// </summary>
        internal static string UNKNOWN_TITLE {
            get {
                return ResourceManager.GetString("UNKNOWN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar pantalla.
        /// </summary>
        internal static string UPDATE_DISPLAY {
            get {
                return ResourceManager.GetString("UPDATE_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usar ID de cliente y secreto personalizados.
        /// </summary>
        internal static string USE_CUSTOM_CREDENTIALS {
            get {
                return ResourceManager.GetString("USE_CUSTOM_CREDENTIALS", resourceCulture);
            }
        }
    }
}
