//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrentlyListening.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CurrentlyListening.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentlyListening.
        /// </summary>
        internal static string APP_NAME {
            get {
                return ResourceManager.GetString("APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        internal static string ARTIST {
            get {
                return ResourceManager.GetString("ARTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization successful. You can close this window..
        /// </summary>
        internal static string AUTH_SUCCESS {
            get {
                return ResourceManager.GetString("AUTH_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID.
        /// </summary>
        internal static string CLIENT_ID {
            get {
                return ResourceManager.GetString("CLIENT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Secret.
        /// </summary>
        internal static string CLIENT_SECRET {
            get {
                return ResourceManager.GetString("CLIENT_SECRET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to tray when closing.
        /// </summary>
        internal static string CLOSE_SHOULD_MINIMIZE {
            get {
                return ResourceManager.GetString("CLOSE_SHOULD_MINIMIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by .
        /// </summary>
        internal static string CREATED_BY {
            get {
                return ResourceManager.GetString("CREATED_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path saved:\n{dialog.FileName}.
        /// </summary>
        internal static string FILE_SAVED {
            get {
                return ResourceManager.GetString("FILE_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string FILE_SAVED_CAPTION {
            get {
                return ResourceManager.GetString("FILE_SAVED_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HELP {
            get {
                return ResourceManager.GetString("HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optionally, before starting, register your own app at.
        /// </summary>
        internal static string HELP_1_0 {
            get {
                return ResourceManager.GetString("HELP_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the &quot;Web API&quot; as the platform, and set the callback URL to: http://127.0.0.1:5000/callback. Once created, you’ll find the Client ID and Client Secret in the app’s dashboard—these are needed for login..
        /// </summary>
        internal static string HELP_1_1 {
            get {
                return ResourceManager.GetString("HELP_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Click &quot;Login to Spotify&quot; to authenticate your account..
        /// </summary>
        internal static string HELP_2 {
            get {
                return ResourceManager.GetString("HELP_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Choose which track details to show: Artist, Song Title and/or Time..
        /// </summary>
        internal static string HELP_3 {
            get {
                return ResourceManager.GetString("HELP_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Use &quot;Set Output File Location&quot; to choose where track info will be written..
        /// </summary>
        internal static string HELP_4 {
            get {
                return ResourceManager.GetString("HELP_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Click &quot;Update Display&quot; to apply changes. The file updates automatically while the app is running..
        /// </summary>
        internal static string HELP_5 {
            get {
                return ResourceManager.GetString("HELP_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: You can use the output file in OBS overlays or stream widgets..
        /// </summary>
        internal static string HELP_TIP {
            get {
                return ResourceManager.GetString("HELP_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Use CurrentlyListening App.
        /// </summary>
        internal static string HOW_TO_USE_APP {
            get {
                return ResourceManager.GetString("HOW_TO_USE_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong with login data, please re-authorize.
        /// </summary>
        internal static string LOGIN_FAILED {
            get {
                return ResourceManager.GetString("LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to Spotify.
        /// </summary>
        internal static string LOGIN_SPOTIFY {
            get {
                return ResourceManager.GetString("LOGIN_SPOTIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in successfully..
        /// </summary>
        internal static string LOGIN_SUCCESS {
            get {
                return ResourceManager.GetString("LOGIN_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app has been minimised. Click the tray icon to show..
        /// </summary>
        internal static string MINIMIZE_NOTIFICATION_TEXT {
            get {
                return ResourceManager.GetString("MINIMIZE_NOTIFICATION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing is currently playing..
        /// </summary>
        internal static string NOTHING_PLAYING {
            get {
                return ResourceManager.GetString("NOTHING_PLAYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output preview:.
        /// </summary>
        internal static string OUTPUT_PREVIEW {
            get {
                return ResourceManager.GetString("OUTPUT_PREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Output File Location.
        /// </summary>
        internal static string SELECT_OUTPUT {
            get {
                return ResourceManager.GetString("SELECT_OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Output File Location.
        /// </summary>
        internal static string SET_OUTPUT_LOCATION {
            get {
                return ResourceManager.GetString("SET_OUTPUT_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Title.
        /// </summary>
        internal static string SONG_TITLE {
            get {
                return ResourceManager.GetString("SONG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start minimized to tray.
        /// </summary>
        internal static string START_MINIMIZED {
            get {
                return ResourceManager.GetString("START_MINIMIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (Progress/Duration).
        /// </summary>
        internal static string TIME {
            get {
                return ResourceManager.GetString("TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Display Options:.
        /// </summary>
        internal static string TRACK_DISPLAY_OPTIONS {
            get {
                return ResourceManager.GetString("TRACK_DISPLAY_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Artist.
        /// </summary>
        internal static string UNKNOWN_ARTIST {
            get {
                return ResourceManager.GetString("UNKNOWN_ARTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Title.
        /// </summary>
        internal static string UNKNOWN_TITLE {
            get {
                return ResourceManager.GetString("UNKNOWN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Display.
        /// </summary>
        internal static string UPDATE_DISPLAY {
            get {
                return ResourceManager.GetString("UPDATE_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use custom Client ID and Secret.
        /// </summary>
        internal static string USE_CUSTOM_CREDENTIALS {
            get {
                return ResourceManager.GetString("USE_CUSTOM_CREDENTIALS", resourceCulture);
            }
        }
    }
}
