//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrentlyListening.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations_pl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations_pl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CurrentlyListening.Resources.Translations.pl", typeof(Translations_pl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artysta.
        /// </summary>
        internal static string ARTIST {
            get {
                return ResourceManager.GetString("ARTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoryzacja zakończona sukcesem. Możesz zamknąć to okno..
        /// </summary>
        internal static string AUTH_SUCCESS {
            get {
                return ResourceManager.GetString("AUTH_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID.
        /// </summary>
        internal static string CLIENT_ID {
            get {
                return ResourceManager.GetString("CLIENT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Secret.
        /// </summary>
        internal static string CLIENT_SECRET {
            get {
                return ResourceManager.GetString("CLIENT_SECRET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamknij.
        /// </summary>
        internal static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stworzone przez .
        /// </summary>
        internal static string CREATED_BY {
            get {
                return ResourceManager.GetString("CREATED_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisano ścieżkę do pliku:\n{dialog.FileName}.
        /// </summary>
        internal static string FILE_SAVED {
            get {
                return ResourceManager.GetString("FILE_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisano.
        /// </summary>
        internal static string FILE_SAVED_CAPTION {
            get {
                return ResourceManager.GetString("FILE_SAVED_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomoc.
        /// </summary>
        internal static string HELP {
            get {
                return ResourceManager.GetString("HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opcjonalnie, przed rozpoczęciem, zarejestruj swoją aplikację na.
        /// </summary>
        internal static string HELP_1_0 {
            get {
                return ResourceManager.GetString("HELP_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz &quot;Web API&quot; jako platformę i ustaw URL zwrotny na: http://127.0.0.1:5000/callback. Po utworzeniu znajdziesz Client ID i Client Secret w panelu aplikacji — są one wymagane do logowania..
        /// </summary>
        internal static string HELP_1_1 {
            get {
                return ResourceManager.GetString("HELP_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Kliknij &quot;Zaloguj się do Spotify&quot;, aby uwierzytelnić swoje konto..
        /// </summary>
        internal static string HELP_2 {
            get {
                return ResourceManager.GetString("HELP_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Wybierz, które informacje o utworze wyświetlić: Artysta, Tytuł i/lub Czas..
        /// </summary>
        internal static string HELP_3 {
            get {
                return ResourceManager.GetString("HELP_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Użyj &quot;Ustaw lokalizację pliku wyjściowego&quot;, aby wybrać miejsce zapisu informacji o utworze..
        /// </summary>
        internal static string HELP_4 {
            get {
                return ResourceManager.GetString("HELP_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Kliknij &quot;Aktualizuj wyświetlanie&quot;, aby zastosować zmiany. Plik jest aktualizowany automatycznie podczas działania aplikacji..
        /// </summary>
        internal static string HELP_5 {
            get {
                return ResourceManager.GetString("HELP_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porada: możesz używać pliku wyjściowego w nakładkach OBS lub widgetach do streamowania..
        /// </summary>
        internal static string HELP_TIP {
            get {
                return ResourceManager.GetString("HELP_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jak korzystać z aplikacji CurrentlyListening.
        /// </summary>
        internal static string HOW_TO_USE_APP {
            get {
                return ResourceManager.GetString("HOW_TO_USE_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił błąd danych logowania, proszę autoryzować ponownie.
        /// </summary>
        internal static string LOGIN_FAILED {
            get {
                return ResourceManager.GetString("LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj się do Spotify.
        /// </summary>
        internal static string LOGIN_SPOTIFY {
            get {
                return ResourceManager.GetString("LOGIN_SPOTIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie zakończone sukcesem..
        /// </summary>
        internal static string LOGIN_SUCCESS {
            get {
                return ResourceManager.GetString("LOGIN_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplikacja została zminimalizowana. Kliknij ikonę w zasobniku systemowym, aby ją wyświetlić..
        /// </summary>
        internal static string MINIMIZE_NOTIFICATION_TEXT {
            get {
                return ResourceManager.GetString("MINIMIZE_NOTIFICATION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nic nie jest aktualnie odtwarzane..
        /// </summary>
        internal static string NOTHING_PLAYING {
            get {
                return ResourceManager.GetString("NOTHING_PLAYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podgląd wyjścia:.
        /// </summary>
        internal static string OUTPUT_PREVIEW {
            get {
                return ResourceManager.GetString("OUTPUT_PREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz lokalizację pliku wyjściowego.
        /// </summary>
        internal static string SELECT_OUTPUT {
            get {
                return ResourceManager.GetString("SELECT_OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz lokalizację pliku wyjściowego.
        /// </summary>
        internal static string SET_OUTPUT_LOCATION {
            get {
                return ResourceManager.GetString("SET_OUTPUT_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł utworu.
        /// </summary>
        internal static string SONG_TITLE {
            get {
                return ResourceManager.GetString("SONG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas (Postęp/Czas trwania).
        /// </summary>
        internal static string TIME {
            get {
                return ResourceManager.GetString("TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opcje wyświetlania utworu:.
        /// </summary>
        internal static string TRACK_DISPLAY_OPTIONS {
            get {
                return ResourceManager.GetString("TRACK_DISPLAY_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieznany artysta.
        /// </summary>
        internal static string UNKNOWN_ARTIST {
            get {
                return ResourceManager.GetString("UNKNOWN_ARTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieznany tytuł.
        /// </summary>
        internal static string UNKNOWN_TITLE {
            get {
                return ResourceManager.GetString("UNKNOWN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualizuj wyświetlanie.
        /// </summary>
        internal static string UPDATE_DISPLAY {
            get {
                return ResourceManager.GetString("UPDATE_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użyj własnego Client ID i Secret.
        /// </summary>
        internal static string USE_CUSTOM_CREDENTIALS {
            get {
                return ResourceManager.GetString("USE_CUSTOM_CREDENTIALS", resourceCulture);
            }
        }
    }
}
